spring:
   config:
     import: optional:configserver:http://localhost:8888
     label: main
   application:
    name: stockMaintain-client  #current service name to be used by the eureka server
   profiles:
    active: development


server:
  port: 2345
  
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
